# Module `neurolab` - example

In [25]:
import numpy as np
import neurolab as nl

In [45]:
# Create train samples
# input is a 10x2 array of random numbers between -0.5 and 0.5
input = np.random.uniform(-0.5, 0.5, (100, 2))
# target is the sum of pairs of inputs
target = (input[:, 0] + input[:, 1]).reshape(100, 1)

In [46]:
print(input.shape)
input

(100, 2)


array([[ -3.13170006e-01,  -2.71142400e-01],
       [ -4.43358528e-01,  -4.96338241e-01],
       [ -3.02247035e-01,   4.35319710e-01],
       [ -1.47286951e-01,   1.10721143e-01],
       [  3.03768791e-01,   1.71549134e-01],
       [ -2.75394428e-01,   1.45593569e-01],
       [  4.29303745e-01,  -2.15775974e-01],
       [  2.99005041e-01,  -2.85181901e-01],
       [ -7.11170922e-02,   1.21395548e-01],
       [  1.93849282e-01,   3.70439055e-01],
       [ -4.22674688e-01,  -3.59115923e-01],
       [  2.12416443e-01,  -3.31219397e-01],
       [ -1.82203515e-01,   4.94173972e-01],
       [  3.55903414e-01,   2.00503110e-01],
       [  3.05183701e-01,  -2.40434164e-01],
       [ -1.98425943e-01,   2.27576480e-01],
       [ -2.04771930e-01,   5.14075442e-02],
       [  2.03476774e-01,   2.30918101e-01],
       [  1.87208192e-01,   3.74328904e-01],
       [ -3.43338657e-02,  -6.64889014e-02],
       [  1.67061426e-02,   4.52998201e-01],
       [  4.74645575e-01,  -3.97914377e-01],
       [ -

In [47]:
target

array([[-0.58431241],
       [-0.93969677],
       [ 0.13307268],
       [-0.03656581],
       [ 0.47531792],
       [-0.12980086],
       [ 0.21352777],
       [ 0.01382314],
       [ 0.05027846],
       [ 0.56428834],
       [-0.78179061],
       [-0.11880295],
       [ 0.31197046],
       [ 0.55640652],
       [ 0.06474954],
       [ 0.02915054],
       [-0.15336439],
       [ 0.43439488],
       [ 0.5615371 ],
       [-0.10082277],
       [ 0.46970434],
       [ 0.0767312 ],
       [-0.16745299],
       [ 0.43812825],
       [ 0.31997326],
       [ 0.7669726 ],
       [ 0.77189916],
       [-0.1795755 ],
       [-0.35953647],
       [-0.0754323 ],
       [ 0.67114307],
       [-0.18252485],
       [-0.24401583],
       [ 0.0458277 ],
       [-0.86244753],
       [ 0.19775731],
       [ 0.41237406],
       [-0.44067869],
       [ 0.38483824],
       [ 0.1008753 ],
       [ 0.10946435],
       [ 0.36688128],
       [-0.04727611],
       [ 0.60585373],
       [-0.37392432],
       [-0

In [82]:
# Create network
# Input range for both inputs is [-0.5, 0.5]
# Five (5) neurons for hidden layer, 1 neuron for output
# Two (2) layers including hidden layer and output layer
net = nl.net.newff([[-0.5, 0.5],  # input 1
                    [-0.5, 0.5]], # input 2
                   [5,  # 5 neurons in first layer
                    1]) # 1 neuron in output layer
net.trainf = nl.train.train_bfgs
print(net.ci) # number of inputs
print(net.co) # number of outputs
net

2
1


In [83]:
# Train process
err = net.train(input, target, show=15)

Epoch: 15; Error: 0.2545699118136369;
Epoch: 30; Error: 0.07795401408868473;
Epoch: 45; Error: 0.05212257692212417;
Epoch: 60; Error: 0.019744252146438546;
The goal of learning is reached


In [84]:
# Test
net.sim([[0.1, 0.3]])

array([[ 0.39323364]])