In [2]:
import numpy as np
c = np.array( [ [1,2,3], [4,5,6], [7,8,9], [10, 11, 12]] )
c
c.append([13,14,15])

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [5]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [4]:
c.dot(a)

array([ 20,  47,  74, 101])