# Module `numpy`

See

- [Quick start tutorial](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)

Begin by importing the `numpy` module. 

In [6]:
import numpy

The basic object of the Numpy module is a (single-dimensional or multi-dimensional) array, which has type `ndarray`. 

The simplest way of creating an `ndarray` is from a list using the `array` function. 

In [24]:
numpy.array([1,2,3])

array([1, 2, 3])

In [21]:
a_list = [1,2,3]
a_ndarray = numpy.array(a_list)
print(type(a_list))
print(type(a_ndarray))

<class 'list'>
<class 'numpy.ndarray'>


## Function `arange`

The `arange` function produces `ndarray` objects. 

In [14]:
type(numpy.arange(3))

numpy.ndarray

The `arange` function returns an `ndarray` consisting of a range of numbers. 

- The first parameter is the first number of the result.
- The third parameter is an increment and defaults to `1`. 
- The result consists of the first parameter followed by all increments up to but not including the second parameter.

Try these examples: 

In [18]:
x = numpy.arange(2, 10, 2) 
x

array([2, 4, 6, 8])

In [19]:
numpy.arange(2, 10) 

array([2, 3, 4, 5, 6, 7, 8, 9])

If only one parameter is provided then the first parameter is set to zero(`0`) and the supplied parameter is the second parameter. 

In [20]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Every `ndarray` object has an attribute called `shape`. Think of it as the dimensions of the array. 

In [22]:
print('x:',x)
print('x.shape:',x.shape)

x: [2 4 6 8]
x.shape: (4,)


The `ndarray` in `x` has one dimension of length `4`.

## Function `linspace`

The `linspace` function is similar to the `arange` function. 

- The first parameter specifies the first number of the result.
- The second parameter specifies the last number of the result.
- The third paramter specifies the number of evenly spaced numbers in the result.

For example, 

In [45]:
numpy.linspace(0,1,3)

array([ 0. ,  0.5,  1. ])

## Datatypes of `ndarray` objects

In this first example the datatype is `int64` which is a (64-bit) integer. 

In [42]:
x = numpy.arange(5)
print("x:",x)
print("datatype:",x.dtype)

x: [0 1 2 3 4]
datatype: int64


The datatype can be changed. In this example we change it to `float` (a real number). This is helpful as some functions require integers and others require real numbers. 

In [43]:
x = numpy.array(x,dtype=float)
print("x:",x)
print("datatype:",x.dtype)

x: [ 0.  1.  2.  3.  4.]
datatype: float64


## Function `reshape` 

The `reshape` function changes the _shape_ of an `ndarray` object.

In [24]:
numpy.arange(0,6).reshape(3,2).transpose()

array([[0, 2, 4],
       [1, 3, 5]])

In [27]:
numpy.arange(0,6).reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [28]:
numpy.arange(0,24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [29]:
numpy.arange(0,24).reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])


## Operations on arrays

There are two types of operations: 

1. Elementwise: the operations are performed on items at corresponding locations. Both input `ndarray` objects and the result have the same shape. 
1. Matrix multiplication: This is an important operation from linear algebra and will be explained below.

### Elementwise operations

First, create two `ndarray` objects to use in the examples.

In [54]:
x = numpy.arange(1,7)
y = numpy.arange(10,61,10)
print('x:',x)
print('y:',y)

x: [1 2 3 4 5 6]
y: [10 20 30 40 50 60]


The arithmetic operations can be applied to `ndarray` objects with the same shape. The result of these operations is created by performing that operations _elementwise_, which means the arithmetic is performed on items in corresponding locations. 

For example,

In [56]:
print('x+y:',x+y)
print('x*y:',x*y)

x+y: [11 22 33 44 55 66]
x*y: [ 10  40  90 160 250 360]


This next example demonstrates arithmetic on `ndarray` objects with a more complicated shape. They are 2x3 matrices.

In [60]:
xm = x.reshape(2,3)
ym = y.reshape(2,3)
print(xm)
print(ym)
print(xm+ym)

[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]]
[[11 22 33]
 [44 55 66]]


### Matrix multiplication 

A very useful and important operation is matrix multiplication, which is performed by the `dot` function 

In [64]:
x = numpy.arange(1,4)
y = numpy.arange(10,13)
print('x:',x)
print('y:',y)
print('the dot product of x and y:',numpy.dot(x,y))

x: [1 2 3]
y: [10 11 12]
the dot product of x and y: 68


The dot product of two vectors (matrices of one dimension) is calculated by multipling the items _elementwise_ and then suming the result. 

In [66]:
sum(x*y)

68

The matrix product of higher dimensional matrices is calculated using the dot product. 

The steps are explained nicely at 

- https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [74]:
x = numpy.array([[2,0],
                 [3,4]])

y = numpy.array([[1,3],
                 [2,4]])

print('x.shape:',x.shape)
print(x)
print('y.shape:',y.shape)
print(y)

x.shape: (2, 2)
[[2 0]
 [3 4]]
y.shape: (2, 2)
[[1 3]
 [2 4]]


In [75]:
numpy.dot(x,y)

array([[ 2,  6],
       [11, 25]])

Matrix multiplication is one of the linear algebra operations. More are explained below in the __Linear algebra 

## Indexing, slicing and iterating on `ndarray` objects

Create the `x` variable for the examples.

In [89]:
x = numpy.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Use the _colon_ operator to retrieve parts of the `ndarray` object stored in `x`.

- The number before the colon is the _starting position_. Remember `0` is the first position.
- The second number (after the colon) is the _ceiling position_. No items at, or after, that position are included in the result. 
- The third number (between the first and second colons) is the _increment_ and defaults to `1`.

The result includes items of the `ndarray` from the _starting position_ to (but not including) the _ceiling position_ in the _increments_ given by the third parameter. 

In [96]:
x[1:5]

array([11, 12, 13, 14])

In [91]:
x[0:7:2]

array([10, 12, 14, 16])

## Linear algebra

See https://docs.scipy.org/doc/numpy-dev/user/quickstart.html#linear-algebra

In [7]:
x = numpy.array([[2,0],
                 [3,4]])
y = numpy.array([[1,3],
                 [2,4]])
print('x.shape:',x.shape)
print(x)
print('y.shape:',y.shape)
print(y)

x.shape: (2, 2)
[[2 0]
 [3 4]]
y.shape: (2, 2)
[[1 3]
 [2 4]]


As we saw the dot product (matrix multiplication) of `x` and `y` is: 

In [8]:
numpy.dot(x,y)

array([[ 2,  6],
       [11, 25]])

In [15]:
y_inv = numpy.linalg.inv(y)
y_inv
print(y_inv)
print(y)

[[-2.   1.5]
 [ 1.  -0.5]]
[[1 3]
 [2 4]]


In [16]:
id = numpy.dot(y,y_inv)
id

array([[ 1.,  0.],
       [ 0.,  1.]])

By hand, with paper and pencil, multiply `id` by `y`. 