ERRORS

http://underflow.fr/ai/lets-play-with-theano-547

In [3]:
import theano.tensor as T
import theano        as th

In [2]:
TS = T.matrix('training-set')
W = T.matrix('weights')
E = T.matrix('expected')

In [6]:
# O is the matrix (column) containing the output for each example
O = T.nnet.sigmoid(T.dot(TS, W))
# def_err is the squared error sum for each example
def_err = ((E - O) ** 2).sum()

In [15]:


err = th.function([W, TS, E], def_err)

In [17]:
err_dW = T.grad(def_err, W)

In [19]:
grad_err = th.function([W, TS, E], err_dW) # ...and this is very dark magic

In [32]:
import scipy as sp 
import numpy as np
#precision = 0.001
# Load the dataset containing the feature for each word of the training set
dataset = np.array([[1,2,3,4],[5,6,7,8]])
# Load the expected output vector E containing 1.0 for french, 0.0 for english for each word of the TS
expected_output = np.array([0,0,1,1])
# Initial random weight vector
weights = sp.random.standard_normal((2, 1))
print(weights) 
print(dataset)
print(expected_output)

[[-0.44804492]
 [-0.08678093]]
[[1 2 3 4]
 [5 6 7 8]]
[0 0 1 1]


In [33]:
err(weights, dataset, expected_output)

TypeError: ('Bad input argument to theano function with name "<ipython-input-15-98ced7287447>:2"  at index 2(0-based)', 'Wrong number of dimensions: expected 2, got 1 with shape (4,).')

In [ ]:
for i in range(100):
    err_val = err(weights, dataset, expected_output)
    err_grad_val = grad_err(weights, dataset, expected_output)
    weights -= precision * error_grad_val
    print("Iteration " + str(i) + ", squared error : " + str(err_val)
