# Keras - classification and regression

Contents:
1. Load required libraries
1. Set initial parameters
1. Create synthetic training datasets
1. Create classification model
1. Train the model and display accuracy
1. Create regression model 
1. Train the model and display mean square error

### Load required libraries

In [1]:
import pandas    as pd
import numpy     as np
import itertools as it

from keras.utils       import np_utils 
from keras.models      import Sequential
from keras.layers.core import Dense, Activation

Using Theano backend.


## Create synthetic training datasets

- Set initial parameters
- Create a random `x_train` dataset with shape determined by parameters and with random values between `0` and `1`.


### Set initial parameters

In [2]:
n_variables =    10
n_samples   =   100
n_epoch     = 1000 # number of training iterations
min_gen     =     1
max_gen     =     4

### Create vector `x_gen` 

The target values of the training datase are created using `x_gen` and `x_train`, which is a matrix of random numbers.

In [3]:
x_gen    = np.random.randint(min_gen, 
                             max_gen, 
                             n_variables)
x_gen

array([2, 1, 1, 3, 1, 3, 3, 2, 2, 1])

### Create `x_train` as a random `n_samples` by `n_variables` matrix 

In [4]:
x_train = np.random.rand(n_samples,
                         n_variables)
x_train.shape
x_train

array([[  8.94891662e-01,   5.25680413e-01,   9.62383760e-01,
          1.16891216e-01,   7.06236827e-01,   4.59722805e-01,
          9.65906793e-01,   8.09460008e-01,   4.40249419e-01,
          9.66237213e-01],
       [  8.08310169e-01,   6.74090611e-02,   1.39509411e-01,
          9.40890957e-01,   5.56976022e-01,   2.67645729e-01,
          3.00196651e-01,   3.46497558e-01,   6.40575670e-01,
          8.60456696e-01],
       [  4.90604829e-01,   9.01335301e-02,   4.33618147e-01,
          2.77028152e-02,   8.91216353e-02,   4.12616603e-01,
          5.02741203e-01,   8.77438927e-02,   3.37528099e-01,
          7.95626259e-01],
       [  3.64098726e-01,   4.12637065e-01,   1.87368557e-01,
          4.74045631e-01,   8.84753196e-01,   5.06400035e-01,
          2.24539307e-01,   3.93005903e-01,   9.55736530e-03,
          4.65035230e-01],
       [  6.92346000e-01,   7.15851420e-01,   6.61932787e-01,
          3.52890682e-01,   6.13384588e-01,   7.17335480e-01,
          4.28201878e-01

### Create training target vectors 

Create `y_train_float` as matrix product of `x_train` and `x_gen`. 

In [5]:
y_train_float = x_train.dot(x_gen).reshape(n_samples,1) 
y_train_float

array([[ 12.07730283],
       [  9.741318  ],
       [  6.06943508],
       [  7.09807295],
       [  8.99138507],
       [  6.84507783],
       [  8.34112302],
       [ 12.20095924],
       [  8.36479175],
       [ 11.10619263],
       [ 12.70645191],
       [ 10.63262148],
       [ 10.87927346],
       [  6.89670328],
       [ 11.52355355],
       [ 11.33820698],
       [ 10.25776729],
       [ 12.2104629 ],
       [  7.49973216],
       [  8.18014726],
       [  7.00606699],
       [ 10.6610356 ],
       [  7.22219274],
       [  7.79272515],
       [  9.79701561],
       [  9.25028996],
       [  6.39764842],
       [  8.09685691],
       [  8.27848681],
       [ 12.83978167],
       [ 13.27399716],
       [  9.77064943],
       [ 10.96601653],
       [ 11.21957434],
       [  8.69335167],
       [ 10.2926138 ],
       [  5.51084772],
       [  9.8459422 ],
       [ 10.00401789],
       [  8.95129676],
       [ 11.94772574],
       [ 11.58730711],
       [  9.59637354],
       [  7

Create `y_train_int` by rounding entries of `y_train_float` to the nearest integer. 

In [6]:
y_train_int = np.round(y_train_float).astype(np.int32)
y_train_int

array([[12],
       [10],
       [ 6],
       [ 7],
       [ 9],
       [ 7],
       [ 8],
       [12],
       [ 8],
       [11],
       [13],
       [11],
       [11],
       [ 7],
       [12],
       [11],
       [10],
       [12],
       [ 7],
       [ 8],
       [ 7],
       [11],
       [ 7],
       [ 8],
       [10],
       [ 9],
       [ 6],
       [ 8],
       [ 8],
       [13],
       [13],
       [10],
       [11],
       [11],
       [ 9],
       [10],
       [ 6],
       [10],
       [10],
       [ 9],
       [12],
       [12],
       [10],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [11],
       [ 7],
       [12],
       [ 8],
       [ 9],
       [10],
       [11],
       [ 9],
       [ 8],
       [10],
       [10],
       [10],
       [11],
       [10],
       [10],
       [ 9],
       [10],
       [12],
       [11],
       [12],
       [13],
       [12],
       [10],
       [ 9],
       [ 7],
       [11],
       [10],
       [10],
       [ 8],

Create `y_train_cat` from `y_train_int` using `to_categorical` by creating binary variables for each (integer) value. 

In [7]:
y_train_cat = np_utils.to_categorical(y_train_int.reshape(n_samples,
                                                          1))
y_train_cat

array([[ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

Notice that the first column of `y_train_cat` contains only zeros.

In [8]:
np.unique(y_train_cat[:,0])

array([ 0.])

Notice the correspondence between the unique values in `y_train_int` and the unique rows is `y_train_cat`.

In [9]:
print("unique integer values:",np.unique(y_train_int))
print("unique rows below")
pd.DataFrame(y_train_cat).drop_duplicates()

unique integer values: [ 6  7  8  9 10 11 12 13]
unique rows below


0    1    2    3    4    5    6    7    8    9    10   11   12   13
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
2   0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
4   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
6   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

## Create classification model

In [10]:
model = Sequential()
middle_layer_count = 64

model.add(Dense(input_dim  = n_variables, 
                output_dim = middle_layer_count, 
                init       = "glorot_uniform"))
model.add(Activation("tanh"))
model.add(Dense(input_dim  = middle_layer_count, 
                output_dim = y_train_cat.shape[1], 
                init       = "glorot_uniform"))
model.add(Activation("softmax"))

### Set the loss function and optimizer 

In [11]:
model.compile(loss='categorical_crossentropy', optimizer='sgd')

### Fit the model 

Use the data in `x_train` and `y_train_cat`.

In [12]:
model.fit(x_train, 
          y_train_cat, 
          nb_epoch      = n_epoch, 
          batch_size    = n_samples, 
          verbose       = False)

### Display accuracy

In [13]:
model.evaluate(x_train,
               y_train_cat, 
               verbose = False)

1.8327729034423828

### Compare stuff

Compare actual and predicted values for the 3rd sample.

In [14]:
arow = 34
print("target value:",y_train_int[arow])
print("prediction  :",model.predict_classes(np.array([x_train[arow]]), 
                                            verbose=False))

target value: [9]
prediction  : [10]


Compare actual and predicted values for the first `10` samples.

In [15]:
pd.DataFrame({"actual"   : y_train_int.reshape(n_samples),
              "predicted": model.predict_classes(x_train,
                                                 verbose=False)}
            )[0:10]

actual  predicted
0      12         10
1      10         10
2       6          7
3       7          9
4       9         10
5       7         10
6       8         10
7      12         10
8       8          9
9      11         10

### Display frequency counts

Display frequence counts for the absolute difference between actual and predicted values.

In [16]:
y_pred = model.predict_classes(x_train, 
                               verbose=False
                              ).reshape(n_samples,)

y_init = y_train_int.reshape(n_samples,)

y_freq = np.bincount(abs(y_pred - y_init))

print("Frequency counts:", y_freq)

Frequency counts: [28 32 25 13  2]


### Check accuracy by hand

In [ ]:
print  ("Accuracy: %.1f percent" % 
        np.round(100*y_freq[0] / sum(y_freq), 
                 decimals=1) )

## Create regression model

The training data consists of:
- `x_train` (same as above)
- `y_train_float` calculated directly from `x_train` and `x_gen` above

In [ ]:
model = Sequential()
middle_layer_count = 64

model.add(Dense(input_dim  = n_variables, 
                output_dim = middle_layer_count, 
                init       = "glorot_uniform"))
model.add(Activation('tanh'))
model.add(Dense(input_dim  = middle_layer_count, 
                output_dim = y_train_float.shape[1])) 

model.compile(loss      = 'mean_absolute_error', 
              optimizer = 'rmsprop')

### Fit the model

In [ ]:
model.fit(x_train, 
          y_train_float, 
          nb_epoch=n_epoch, 
          batch_size=n_samples, 
          verbose=False)

### Display the actual and predicted values side by side

Include the square error for each row and the mean square error.

In [ ]:
pred_err = pd.DataFrame({
        "actual"   : y_train_float         .reshape(n_samples),
        "predicted": model.predict(x_train).reshape(n_samples),
        "sq_err"   : 0
    })
pred_err['sq_err'] = (pred_err['actual'] - pred_err['predicted'])**2
print('Mean square error:', np.mean(pred_err['sq_err']))
pred_err[0:10]

The end.