# Theano - logistic regression example

http://deeplearning.net/software/theano/tutorial/examples.html#a-real-example-logistic-regression

In [2]:
import numpy         as np
import theano        as th
import theano.tensor as T

In [3]:
N_samples      = 100     # training sample size
N_variables    = 3  # number of input variables
training_steps = 100


# generate a dataset: D = (input_values, target_class)
x_train = np.random.randn  (N_samples, 
                            N_variables)
y_train = np.random.randint(size=N_samples, 
                            low=0, 
                            high=2)

print('shape x_train:',x_train.shape)
print('shape y_train:',y_train.shape)
print('shape       w:',np.random.randn(N_variables).shape)

shape x_train: (100, 3)
shape y_train: (100,)
shape       w: (3,)


In [4]:
# Declare Theano symbolic variables
x = T.matrix("x")
y = T.vector("y")

# initialize the weight vector w randomly
w = th.shared(np.random.randn(N_variables), name="w")

# initialize the bias term to zero
b = th.shared(0.0, name="b")

print("Initial model:")
print(w.get_value())
print(b.get_value())

Initial model:
[-1.70464853  2.12561949  2.46332692]
0.0


In [5]:
# Construct Theano expression graph
p_1 = 1 / (1 + T.exp(-T.dot(x, w) - b))       # Probability that target = 1
prediction = p_1 > 0.5                        # The prediction thresholded
xent = -y * T.log(p_1) - (1-y) * T.log(1-p_1) # Cross-entropy loss function
cost = xent.mean() + 0.01 * (w ** 2).sum()    # The cost to minimize
gw, gb = T.grad(cost, [w, b])                 # Compute the gradient of the cost
                                              # w.r.t weight vector w and
                                              # bias term b
                                              # (we shall return to this in a
                                              # following section of this tutorial)

In [7]:
# Compile
train = th.function(
          inputs=[x,y],
          outputs=[prediction, xent],
          updates=((w, w - 0.1 * gw), 
                   (b, b - 0.1 * gb)
                  )
)


In [8]:
# Predict
predict = th.function(inputs=[x], 
                      outputs=prediction)

In [9]:
predict(x_train[0:3,])

array([0, 0, 1], dtype=int8)

In [10]:
# Train
for i in range(training_steps):
    pred, err = train(x_train, 
                      y_train)
    #print('err :',err)
    print('ndiff:',(pred != y_train).sum())

ndiff: 43
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 44
ndiff: 46
ndiff: 46
ndiff: 46
ndiff: 46
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 46
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 45
ndiff: 46
ndiff: 46
ndiff: 46
ndiff: 48
ndiff: 48
ndiff: 48
ndiff: 48
ndiff: 48
ndiff: 48
ndiff: 48
ndiff: 48
ndiff: 49
ndiff: 49
ndiff: 49
ndiff: 49
ndiff: 49
ndiff: 49
ndiff: 49
ndiff: 49
ndiff: 48
ndiff: 48


In [9]:
print("Final model (w vector and b scalar):")
print(w.get_value())
print(b.get_value())
print("predictions (on x_train):")
print(predict(x_train))
print("target values (y_train):")
print(y_train)

Final model (w vector and b scalar):
[-0.02573991 -0.15282187 -0.04790051]
-0.2146326793718898
predictions (on x_train):
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 1 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
target values (y_train):
[0 0 1 1 1 0 0 0 1 0 1 0 1 1 0 0 0 0 1 1 0 0 1 0 1 0 1 0 1 1 0 0 0 1 1 1 0
 0 1 0 0 0 0 1 1 1 0 1 1 1 0 0 0 1 1 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0
 0 1 0 1 0 0 0 0 0 1 1 0 1 0 1 1 1 0 0 1 1 1 0 0 0 0]


In [13]:
(pred == y_train).sum(),"out of", y_train.shape

(52, 'out of', (100,))